### PR TITLE
Create Where are the new AES keys.txt

### PR DESCRIPTION
**Pull request by Videogamer555**

### CODE REVIEW

**Comment by dippyshere** [comment]
Epic added a new anticheat method called Hyperion (by byfron), which runs on-top of Easy Anti-Cheat and BattlEye. This anticheat encrypts the games memory on startup making AES key extraction for the main PAKs/UCAS files no longer possible (previously the key would be found in memory).

**Comment by Videogamer555** [comment]
> Epic added a new anticheat method called Hyperion (by byfron), which runs on-top of Easy Anti-Cheat and BattlEye. This anticheat encrypts the games memory on startup making AES key extraction for the main PAKs/UCAS files no longer possible (previously the key would be found in memory).

Interesting. But where does the game client itself get the AES keys from? Doesn't it just directly download them over an encrypted network connection to a key server endpoint using the official Epic Games Fortnite API (which I think uses HTTPS as the protocol)?  I assumed that likewise, the Ben Bot used this same official API, mimicking the behavior of the official game client, to download the AES keys. Unless the API endpoints are themselves changed, Ben Bot should be able to continue operating as normal, regardless of how many protections they put into the official game client itself. This has me worried that the REAL reason for no more AES keys, is that operator of the Ben Bot may have received a legal threat from Epic, and so he shut down his bot.

**Comment by dippyshere** [comment]
> Interesting. But where does the game client itself get the AES keys from? Doesn't it just directly download them over an encrypted network connection to a key server endpoint using the official Epic Games Fortnite API (which I think uses HTTPS as the protocol)? 

Since the main AES key is required for the game to launch, its contained locally. However the dynamic keys are usually downloaded from the api (storefront/v2/keychain). I believe the main aes key used to be found in the compiled .so lib for the Android builds.

**Comment by dippyshere** [comment]
I'm going to close this for now; For future context: this PR was created when issues were disabled on the repo.

**Pull request closed without merging**
